version: "3.8"
services:
  application:
    image: my-student-server
    container_name: spring-container
    ports:
      - "2222-2222"
    networks:
      - boot-mysql
    depends_on:
      - mysqldb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb-container
    ports:
      - "3306:3306"
    networks:
      - boot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
networks:
  boot-mysql:
    name: boot-mysql
    external: true



